### ISSUE TITLE
bat_algorithm

### ISSUE THREAD

**Issue by yanggengzhen** [kielkowiczk/bat_algorithm#1]

**Comment by kielkowiczk** [comment]
Hi, what seams to be the problem? :))

**Comment by yanggengzhen** [comment]
sorry! 
I'm new to github.
it's a wrong operation :)

**Comment by yanggengzhen** [comment]
hi,kielkowicz! I get a problem in reading the code.
For the third parameter in the function std::for_each(a.begin(),a.end(),[&](float i ){do something }), I dont exactly know what the parameters in these three brackets( [ ], ( ) and { }) respective are.
Could you help me?
Thank you for advance

**Comment by yanggengzhen** [comment]
I’v solved it.
It's a lamda function
Thank you

**Comment by kielkowiczk** [comment]
Great:)) If You need any help feel free to ask :)
Can I ask what You are using Bat alg. for?

## 

mgr inż. Kazimierz Kiełkowicz

Asystent naukowo-dydaktyczny
pok. 410
Zakład Informatyki E-13
Wydział Inżynierii Elektrycznej i Komputerowej
Politechnika Krakowska
31-155 Kraków, ul. Warszawska 24

2015-03-20 10:29 GMT+01:00 yanggengzhen notifications@github.com:
